spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/person
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: liquibase-changeLog.xml